<?php

namespace AppBundle\Repository;

/**
 * CarteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCarteIdsAndJoueurId($tabIds, $joueurId){
        
        return $this->getEntityManager()->createQuery(""
                . "SELECT   c "
                . "FROM     AppBundle:Carte c "
                . "         JOIN c.joueur j "
                . "WHERE    c.id IN (:ids) AND "
                . "         j.id=:joueurId")
                ->setParameter("ids", $tabIds)
                ->setParameter("joueurId", $joueurId)
                ->getResult();
    }
    
    /**
     * Renvoie un tableau comprenant (id, type) des cartes du
     * joueur dont tu passes l'id en paramètre.
     * @param type $joueurId
     */
    public function findDataByJoueurId($joueurId){
        
        return $this->getEntityManager()->createQuery(""
                . "SELECT   c.id, c.type "
                . "FROM     AppBundle:Carte c "
                . "         JOIN c.joueur j "
                . "WHERE    j.id=:joueurId")
                ->setParameter("joueurId", $joueurId)
                ->getScalarResult();
    }
}
