<?php

namespace AppBundle\Repository;

/**
 * JoueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoueurRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDataByPartieIdOrderByJoueurOrdre($partieId){
        
        return $this->getEntityManager()->createQuery(
                "  SELECT   j.elimine, j.id, j.nom, j.ordre, COUNT(c) nbCartes "
                . "FROM     AppBundle:Joueur j "
                . "         JOIN j.partie p "
                . "         LEFT JOIN j.cartes c "
                . "WHERE    p.id=:partieId "
                . "GROUP BY j "
                . "ORDER BY j.ordre")
                ->setParameter("partieId", $partieId)
                ->getScalarResult();
    }
    
    public function findByPartieIdOrderByJoueurOrdre($partieId){
        
        return $this->getEntityManager()->createQuery(
                "  SELECT   j "
                . "FROM     AppBundle:Joueur j "
                . "         JOIN j.partie p "
                . "WHERE    p.id=:partieId "
                . "ORDER BY j.ordre")
                ->setParameter("partieId", $partieId)
                ->getResult();
    }
}
