<?php

namespace AppBundle\Repository;

/**
 * PartieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartieRepository extends \Doctrine\ORM\EntityRepository {

    public function findDataById($partieId){
        
        return $this->getEntityManager()->createQuery(""
                . "SELECT   p.id, p.etat, p.ordre "
                . "FROM     AppBundle:Partie p "
                . "WHERE    p.id=:partieId")
                ->setParameter("partieId", $partieId)
                ->getScalarResult()[0];
    }
    
    public function listerPartiesEnAttente() {
        
        $qb = $this->getEntityManager()->createQueryBuilder();
        return $qb
                ->select("p")
                ->from("AppBundle:Partie", "p")
                ->where("p.etat=:etat")
                ->setParameter("etat", \AppBundle\Entity\Partie::ETAT_EN_ATTENTE)->getQuery()->getResult();
    }

}
