<?php

namespace AppBundle\Repository;

/**
 * PartieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartieRepository extends \Doctrine\ORM\EntityRepository {

    public function listerPartiesEnAttente() {
        
        $qb = $this->getEntityManager()->createQueryBuilder();
        return $qb
                ->select("p")
                ->from("AppBundle:Partie", "p")
                ->where("p.etat=:etat")
                ->setParameter("etat", \AppBundle\Entity\Partie::ETAT_EN_ATTENTE)->getQuery()->getResult();
    }

}
